name: github_action_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  # Computation
  - numpy
  - pandas

  # Plotting
  - matplotlib

  # Debugging
  - jupyter
  - pylint
  - rope
  - black[jupyter]

  - pyarrow

  # - pip: